sorcery:
  twitter:
    callback_url: 'http://127.0.0.1:3000/oauth/callback?provider=twitter'
  facebook:
    callback_url: 'https://localhost:9292/oauth/callback?provider=facebook'
  google:
    callback_url: 'http://127.0.0.1:3000/oauth/callback?provider=google'