sorcery:
  twitter:
    callback_url: 'https://how-to-keep-big-fish.herokuapp.com/oauth/callback?provider=twitter'
  facebook:
    callback_url: 'https://how-to-keep-big-fish.herokuapp.com/oauth/callback?provider=facebook'
  google:
    callback_url: 'https://how-to-keep-big-fish.herokuapp.com/oauth/callback?provider=google'